// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:management_tasks_app/shared/local_database/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AddressModelAdapter());
    registerAdapter(BankModelAdapter());
    registerAdapter(CompanyModelAdapter());
    registerAdapter(CoordinatesModelAdapter());
    registerAdapter(CryptoModelAdapter());
    registerAdapter(HairModelAdapter());
    registerAdapter(ProfileModelAdapter());
    registerAdapter(TodoDetailsModelAdapter());
    registerAdapter(TodoModelAdapter());
  }
}
